### PR TITLE
change one

### PR DESCRIPTION
**Pull request by huilingh**

### CODE REVIEW

**Comment by moradology** [comment]
Looks like you opened a couple PRs. Closing this one in favor of the newer one

**Comment by huilingh** [comment]
Sorry I think I accidentally created a new pull request in class last week and my pull request for assignment one is added below the first one. My latest pull request is called Huiling Assignment 1 and please ignore this one.

**Comment by moradology** [comment]
No problem - once a PR is created, you can always update it by simply pushing up some new commits! No need to create new PRs when you make some changes

**Comment by huilingh** [comment]
Get it, thanks! That's why I couldn't find my PR for the assignment for the first time - didn't notice that it was under my first PR

**Pull request closed without merging**
